name: conformal-design 
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - pip=20.1.1
  - python=3.7.7
  - numpy=1.18.1
  - numpy-base=1.18.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - scipy=1.4.1
  - pytorch=1.4.0
  - torchvision=0.5.0
  - pandas=1.0.3
  - pillow=7.1.2
  - seaborn=0.10.1
  - tqdm=4.47.0
  - tensorflow-gpu==2.1
  - ipykernel
  - parse==1.19
  - scikit-learn==1.0.1
  - xlrd
